[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade || true",
  "python -m pip install --upgrade pip",
  "python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && python manage.py bootstrap_admin && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
