from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_dataimportbatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marital_status', models.CharField(blank=True, max_length=80)),
                ('children_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moh_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('employment_start_date', models.DateField(blank=True, null=True)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_position', models.CharField(blank=True, max_length=150)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('obesity_status', models.CharField(blank=True, max_length=80)),
                ('physical_activity', models.CharField(blank=True, max_length=120)),
                ('diabetes', models.BooleanField(blank=True, null=True)),
                ('hypertension', models.BooleanField(blank=True, null=True)),
                ('thyroid_disease', models.BooleanField(blank=True, null=True)),
                ('asthma', models.BooleanField(blank=True, null=True)),
                ('blood_disease', models.BooleanField(blank=True, null=True)),
                ('smoking_status', models.CharField(blank=True, max_length=120)),
                ('surgical_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('medical_restrictions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_health_profile', to='health.employee')),
            ],
            options={
                'verbose_name': 'Employee health profile',
                'verbose_name_plural': 'Employee health profiles',
            },
        ),
        migrations.CreateModel(
            name='LabScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_status', models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed'), ('missing', 'Missing'), ('not_required', 'Not required')], default='requested', max_length=30)),
                ('request_date', models.DateField(blank=True, null=True)),
                ('result_status', models.CharField(blank=True, max_length=60)),
                ('result_checked_date', models.DateField(blank=True, null=True)),
                ('anti_hbs', models.CharField(blank=True, max_length=120)),
                ('hbsag', models.CharField(blank=True, max_length=120)),
                ('hcv', models.CharField(blank=True, max_length=120)),
                ('hiv', models.CharField(blank=True, max_length=120)),
                ('rubella_igg', models.CharField(blank=True, max_length=120)),
                ('measles_igg', models.CharField(blank=True, max_length=120)),
                ('varicella_igg', models.CharField(blank=True, max_length=120)),
                ('ppd_test', models.CharField(blank=True, max_length=120)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_screenings', to='health.employee')),
            ],
            options={
                'ordering': ['-request_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaccine_type', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('incomplete', 'Incomplete'), ('due', 'Due'), ('refused', 'Refused'), ('contraindicated', 'Contraindicated')], default='due', max_length=30)),
                ('campaign_name', models.CharField(blank=True, max_length=150)),
                ('first_dose_date', models.DateField(blank=True, null=True)),
                ('second_dose_date', models.DateField(blank=True, null=True)),
                ('third_dose_date', models.DateField(blank=True, null=True)),
                ('booster_date', models.DateField(blank=True, null=True)),
                ('post_vaccine_result', models.CharField(blank=True, max_length=150)),
                ('refusal_reason', models.TextField(blank=True)),
                ('contraindication_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='health.employee')),
            ],
            options={
                'ordering': ['employee', 'vaccine_type'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dose_label', models.CharField(max_length=80)),
                ('dose_date', models.DateField(blank=True, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=80)),
                ('given_by', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='health.vaccinationrecord')),
            ],
            options={
                'ordering': ['record', 'dose_date'],
            },
        ),
        migrations.CreateModel(
            name='OccupationalClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_type', models.CharField(blank=True, max_length=120)),
                ('action', models.TextField(blank=True)),
                ('physician', models.CharField(blank=True, max_length=150)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupational_clinic_visits', to='health.employee')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('sick_leave_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('physician', models.CharField(blank=True, max_length=150)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_clinic_visits', to='health.employee')),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalCommitteeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_number', models.CharField(blank=True, db_index=True, max_length=120)),
                ('contract_type', models.CharField(blank=True, max_length=120)),
                ('diagnosis', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('decision', models.TextField(blank=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('physician', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('decision_issued', 'Decision Issued'), ('closed', 'Closed')], default='under_review', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_committee_cases', to='health.employee')),
            ],
            options={
                'ordering': ['-decision_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NeedleStickExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exposure_date', models.DateField(blank=True, null=True)),
                ('work_nature', models.CharField(blank=True, max_length=150)),
                ('workplace', models.CharField(blank=True, max_length=150)),
                ('injury_method', models.CharField(blank=True, max_length=200)),
                ('anti_hbs_result', models.CharField(blank=True, max_length=120)),
                ('source_known', models.BooleanField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_national_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('source_result', models.CharField(blank=True, max_length=200)),
                ('referred_to_employee_clinic', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('referred', 'Referred'), ('closed', 'Closed')], default='new', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needle_stick_exposures', to='health.employee')),
            ],
            options={
                'ordering': ['-exposure_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreeningProgramRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program_type', models.CharField(choices=[('colon_cancer', 'Colon cancer'), ('influenza', 'Influenza'), ('other', 'Other')], default='other', max_length=40)),
                ('program_year', models.PositiveIntegerField(default=2025)),
                ('status', models.CharField(choices=[('eligible', 'Eligible'), ('completed', 'Completed'), ('refused', 'Refused'), ('excluded', 'Excluded'), ('pending', 'Pending')], default='pending', max_length=30)),
                ('result', models.CharField(blank=True, max_length=200)),
                ('action_taken', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_program_records', to='health.employee')),
            ],
            options={
                'ordering': ['-program_year', 'program_type'],
            },
        ),
        migrations.CreateModel(
            name='CampaignCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_name', models.CharField(max_length=150)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('target_count', models.PositiveIntegerField(default=0)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('refused_count', models.PositiveIntegerField(default=0)),
                ('contraindicated_count', models.PositiveIntegerField(default=0)),
                ('coverage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_coverages', to='health.healthcenter')),
            ],
            options={
                'ordering': ['-year', 'campaign_name'],
            },
        ),
        migrations.CreateModel(
            name='TraineeRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=30)),
                ('specialty', models.CharField(blank=True, max_length=150)),
                ('rotation_start_date', models.DateField(blank=True, null=True)),
                ('rotation_end_date', models.DateField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('supervisor', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('health_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee_rotations', to='health.healthcenter')),
            ],
            options={
                'ordering': ['-rotation_start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_sheet', models.CharField(blank=True, max_length=150)),
                ('imported_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('center', 'Center'), ('job_title', 'Job title'), ('vaccine', 'Vaccine'), ('lab_test', 'Lab test'), ('diagnosis', 'Diagnosis'), ('other', 'Other')], default='other', max_length=80)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('label_ar', models.CharField(max_length=200)),
                ('label_en', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'label_ar'],
            },
        ),
        migrations.AddIndex(
            model_name='labscreening',
            index=models.Index(fields=['request_status', 'request_date'], name='health_labs_request_90563f_idx'),
        ),
        migrations.AddConstraint(
            model_name='vaccinationrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'vaccine_type', 'campaign_name'), name='unique_employee_vaccine_campaign'),
        ),
        migrations.AddIndex(
            model_name='medicalcommitteecase',
            index=models.Index(fields=['transaction_number'], name='health_medi_transac_b9452c_idx'),
        ),
        migrations.AddIndex(
            model_name='needlestickexposure',
            index=models.Index(fields=['exposure_date', 'status'], name='health_need_exposur_26a6c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='screeningprogramrecord',
            constraint=models.UniqueConstraint(fields=('employee', 'program_type', 'program_year'), name='unique_employee_program_year'),
        ),
        migrations.AddConstraint(
            model_name='campaigncoverage',
            constraint=models.UniqueConstraint(fields=('campaign_name', 'health_center', 'year'), name='unique_campaign_center_year'),
        ),
        migrations.AddConstraint(
            model_name='referencelookup',
            constraint=models.UniqueConstraint(fields=('category', 'code', 'label_ar'), name='unique_reference_lookup_item'),
        ),
    ]
